name: Tests

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    runs-on: "ubuntu-22.04"
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
      with:
        # at least support HEAD~1 for testing
        fetch-depth: 2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        make
    - name: Run tests
      run: |
        make ci
    - name: diffctx
      uses: williamfzc/diffctx@v0.3.8
      with:
        lang: python
